# Generated by Django 5.0.3 on 2024-03-19 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=250)),
                ('deskripsi', models.CharField(max_length=250)),
                ('gambar', models.ImageField(upload_to='items')),
                ('jenis_produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.produk')),
            ],
        ),
    ]
