# Generated by Django 5.0.3 on 2024-03-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=250)),
                ('deskripsi', models.CharField(max_length=250)),
                ('gambar', models.ImageField(upload_to='produk')),
            ],
        ),
    ]
